version: '3.2'

services:
  resurface:
    image: resurfaceio/resurface:3.1.17
    container_name: springboot_resurface
    ports:
      - '7700:7700'
      - '7701:7701'


  springboot:
    image: test-springboot
    container_name: springboot
    ports:
      - '80:9001'
    env_file:
      - .env
    volumes:
      - ${HOME}/.gradle:/root/.gradle
